import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
const RecetaPrint = ({ empresa, paciente, propietario, medico, consulta, tratamientos, }) => {
    return (_jsxs("div", { className: "w-full h-auto p-4 md:p-8 bg-white border border-gray-300 shadow-md print:shadow-none print:border-0 font-sans", children: [_jsxs("div", { className: "flex justify-between items-start mb-6", children: [_jsxs("div", { className: "flex h-32 absolute top-0 left-0", children: [_jsx("div", { className: "w-8 bg-[#3c6ca6] h-full" }), _jsx("div", { className: "w-8 bg-[#2d568c] h-full relative", children: _jsx("div", { className: "w-0 h-0 border-t-[32px] border-l-[32px] border-t-white border-l-[#2d568c] absolute bottom-0" }) })] }), _jsxs("div", { className: "ml-16 pr-8", children: [_jsxs("p", { className: "font-bold text-lg", children: ["Dr(a). ", medico.nombre] }), _jsx("p", { className: "text-gray-600", children: "M\u00C9DICO VETERINARIO" }), _jsx("p", { className: "font-bold text-lg text-gray-700 mr-2", children: empresa.nombre }), _jsx("hr", { className: "mb-4 mt-6" }), _jsxs("p", { children: [_jsx("strong", { children: "Nombre (paciente):" }), " ", paciente.nombre, " ", _jsx("strong", { children: "Propietario:" }), " ", propietario.nombre] }), _jsxs("p", { children: [_jsx("strong", { children: "C\u00E9dula:" }), " ", propietario.cedula] }), _jsxs("p", { children: [_jsx("strong", { children: "Tel\u00E9fono:" }), " ", propietario.telefono] }), _jsxs("p", { children: [_jsx("strong", { children: "Direcci\u00F3n:" }), " ", propietario.direccion] }), _jsxs("p", { children: [_jsx("strong", { children: "Fecha:" }), " ", consulta.created_at
                                        ? new Date(consulta.created_at).toLocaleString("es-EC", {
                                            year: "numeric",
                                            month: "2-digit",
                                            day: "2-digit",
                                            hour: "2-digit",
                                            minute: "2-digit",
                                            second: "2-digit",
                                            hour12: false, // para formato 24h
                                        })
                                        : "Sin fecha"] })] }), _jsx("div", { className: "flex flex-col items-end", children: _jsx("div", { className: "flex items-center", children: _jsx("div", { className: "flex-shrink-0 transform transition duration-300 group-hover:scale-105", children: _jsx("img", { src: `http://localhost:3010/uploads/logos/${empresa.foto}`, alt: empresa.nombre, className: "w-24 h-24 object-cover rounded-lg border" }) }) }) })] }), _jsx("div", { className: "min-h-[25rem] border border-gray-300 mb-6 p-4", children: _jsxs("div", { className: "mb-6", children: [_jsx("h2", { className: "font-semibold mb-2 text-2xl", children: "Receta:" }), tratamientos.length === 0 ? (_jsx("p", { children: "No hay tratamientos registrados" })) : (tratamientos.map((t, i) => (_jsx("div", { className: "mb-3", children: _jsx("ul", { className: "list-disc list-inside text-2xl", children: t.medicamentos.map((m) => (_jsxs("li", { children: [m.med_nombre, " \u2013 ", m.med_dosis] }, m.med_id))) }) }, i))))] }) }), _jsx("div", { className: "flex justify-between items-center  text-gray-600", children: _jsxs("div", { className: "flex items-center", children: [_jsxs("span", { className: "mr-4", children: ["\uD83D\uDCDE ", empresa.telefono] }), _jsxs("span", { className: "mr-4", children: ["\uD83D\uDCE7 ", empresa.email] }), _jsxs("span", { children: ["\uD83D\uDCCD ", empresa.direccion] })] }) }), _jsx("hr", { className: "mb-4 mt-6" }), _jsxs("div", { className: "items-center justify-center ", children: [_jsx("p", { className: "font-bold text-lg text-gray-700 mr-2", children: "Generado por AmigoVet www.amigovet123.com - Sistema Clinico Veterinario" }), _jsx("p", { className: "font-bold text-lg text-gray-700 mr-2", children: "By Guardiao-Tech www.guardiaotech.com" })] })] }));
};
export default RecetaPrint;
